#!/bin/sh
#
# galaxy-console - this script starts and stops the galaxy-console daemon
#
# chkconfig:    2345 80 90
# description:  Activates/Deactivates Galaxy console
# processname:  galaxy-console
# config:       /etc/galaxy.conf
#
# Provides:           galaxy-console
# Required-Start:     $remote_fs $syslog
# Required-Stop:      $remote_fs $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Start Galaxy console.
# Description:        Start Galaxy console.

# Source function library.
. /etc/rc.d/init.d/functions

GALAXY_CONFIG="/etc/galaxy.conf"
GALAXY_USER=`ruby -ryaml -e "puts YAML.load(File.open('$GALAXY_CONFIG'))['galaxy.console.user'] || ''"`

galaxy_console="/usr/bin/galaxy-console"
prog=$(basename $galaxy_console)

start() {
  echo -n $"Starting Galaxy Console: "
  su - $GALAXY_USER -c "$galaxy_console --start" >/dev/null 2>&1 && success || failure $"$prog start"
  retval=$?
  echo
  return $retval
}

stop() {
  echo -n $"Shutting down Galaxy Console: "
  su - $GALAXY_USER -c "$galaxy_console --stop" >/dev/null 2>&1 && success || failure $"$prog stop"
  retval=$?
  echo
  return $retval  
}

restart() {
  stop
  sleep 2
  start
}

rh_status() {
  status $prog
}

rh_status_q() {
  rh_status >/dev/null 2>&1
}

if [ -z "$GALAXY_USER" ]; then
  echo -n "Error: Unable to determine galaxy console user." && failure
  echo
  echo "Please set the \`galaxy.console.user\` property in $GALAXY_CONFIG."
  exit 1
fi

case "$1" in
  start)
      rh_status_q && exit 0
      $1
      ;;
  stop)
      rh_status_q || exit 0
      $1
      ;;
  restart)
      $1
      ;;
  status|status_q)
      rh_$1
      ;;
  *)
      echo $"Usage: $0 <start|stop|status|restart>"
      exit 2
esac
